### ISSUE TITLE
Check key repeat

### ISSUE THREAD

**Issue by akx** [suomipelit/kops#19]
Original SDL1 port had SDL key repeat commands which doesn't exist anymore with SDL2. Check the impact. Brief testing felt the same on our SDL2 port and with original SDL1 release.

**Comment by veikkos** [comment]
SDL1 port disables key repeat while in game, so our SDL2 works the same now. But in menus our key repeat speed is too high. SDL2 doesn't support settings the delay, but we need to implement it ourselves with a times (like in UTK port).
