### ISSUE TITLE
Game speed differs from original

### ISSUE THREAD

**Issue by veikkos** [suomipelit/kops#24]
Game runs too fast compared to SDL1 release. It would be better to compare against DOS version but we should find it first...

**Comment by veikkos** [comment]
DOS KOPS runs at 75 fps on DOSBox. Our port at 66 fps.

**Comment by akx** [comment]
Could we make this a tuneable parameter? Say, F9/F10 to decrease/increase speed?

**Comment by veikkos** [comment]
> 
> 
> Could we make this a tuneable parameter? Say, F9/F10 to decrease/increase speed?

Yea, why not. :)
